# Default values for istio-azure-monitor-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

istioNamespace: "istio-system"

image:
  repository: alkaplan/application-insights-istio-mixer-adapter
  tag: pp1
  pullPolicy: Always

instrumentation:
  # instrumentation key for the Application Insights resource to send telemetry to
  applicationInsightsKey: "00000000-0000-0000-0000-000000000000"
  liveMetricsStreamKey: "0000"
  # comma-separated list of Kubernetes namespaces to monitor. Leave empty if all namespaces must be monitored
  watchingNamespaces: "default"
   # Log level: Info is the default, Trace for detailed tracing, Error for errors only
  logLevel: Trace

nameOverride: ""
fullnameOverride: ""
