apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-azure-monitor-chart.fullname" . }}
  namespace: {{ .Values.istioNamespace }}
  labels:
    app.kubernetes.io/name: {{ include "istio-azure-monitor-chart.name" . }}
    helm.sh/chart: {{ include "istio-azure-monitor-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
     app.kubernetes.io/name: {{ include "istio-azure-monitor-chart.name" . }}
  ports:
  - name: http2-in-port
    protocol: TCP
    port: 6789
    targetPort: 6789
